spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:contacts;DB_CLOSE_DELAY=-1
        name:
        username: sa
        password:
    h2:
        console:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: none        
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
                  
server:
    port: 8080        
    
contacts:
    bootstrap:
        enable: true
                                                    
                            